name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: go get -u github.com/antchfx/htmlquery

    - name: Build the app
      run: go build

    - name: Run tests
      run: go test -v .
    
    - name: Archive binary
      uses: actions/upload-artifact@v1
      with:
        name: apod-bot
        path: apod-bot
